### ISSUE TITLE
Run e2e test with dashboard and slu-scripts to verify the overall process

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/cxc-slu-authenticity#107]

**Comment by jacekroszkowiakdev** [comment]
The results of running various scenarios:

1. It is not possible to return form register a new DID page to the home page. Site needs to be manually reloaded.
2. Search is not implemented.
3. For page width 767 and below the hamburger menu on the top right appears instead the Logout button. Logout button then appears at the left of the side once hamburger menu is clicked. Clicking on the menu hides the logout button again.
4. Progress bar reaches 100% in about 5 second before the task is done.
5. Closing the create device dialog box with X prevents form opening that dialog box again. Site needs to be manually reloaded to allow that back.
6. Creating a device with same name as an existing one will result in Status Code 409 Conflict and UI showing a There was an error  creating the channel. A more specific information would be better from the user experience standpoint.
