### ISSUE TITLE
create is-one-shot-device-registration microservice

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/cxc-slu-authenticity#12]
(*You can create the microservice in NestJS*)

*https://github.com/iota-community/is-one-shot-device-registration*

Microservice that is able to create a channel and an identity and download them via one-shot endpoint.
Data are stored in MongoDB

*POST /create*

This endpoint creates a channel, an identity and a nonce (random): these are stored on disk.
The nonce is returned by the function

*GET /bootstrap/[NONCE]*

This method will return channel address and identity for that nonce in the database and clear the record on database
 
*Note*

Channel need to be not only created, but identity need to request subscription and admin need to approve subscription

Create Identity: https://github.com/iotaledger/integration-services/blob/develop/clients/node/examples/1-CreateIdentityAndCredential.ts
Create Channel: https://github.com/iotaledger/integration-services/blob/develop/clients/node/examples/6-AuthorizeToChannel.ts

**Comment by dominic22** [comment]
1. create identity using is-sdk
- this identity will return the private key + further information about it
2. use the private key to authenticate via sdk and the generated identity
3. create a new channel using the authenticated identity
4. create a nonce like a guid
5. store all this information in a database called: `slu-bootstrap`
data model should look like:

{
nonce: string,
channel-id: string,
channel-seed:string,
identity-keys: IdentityKeys
}

This information will then be returned by /bootstrap/NONCE and then removed from the database after it was returned to the caller.
