### ISSUE TITLE
Periodic job that send auth proof to SLU

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/cxc-slu-authenticity#15]
Create a node script that will periodically (configurable) send proof of authenticity to collector

This script will interact with is-slu-secure-storage to get encrypted identity (that will use to sign timestamp)

An example of how, giving an identity, how to produce a proof of authenticity is performed here.

https://github.com/iota-community/is-ssi-proof-of-ownership/blob/main/examples/index.ts

*Note*

Data are stored encrypted by VPUF in a file called `data.json.enc`

data.json look like

```
{
   "identity": ...,
   "channelAddress": ...
}
```

Identity looks like:

```
{
  "doc": {
    "id": "did:iota:DadHWpApPFnGccHuK5vy1Ya4LrAUGrsnHTa24n6JtUMy",
    "authentication": [
      {
        "id": "did:iota:DadHWpApPFnGccHuK5vy1Ya4LrAUGrsnHTa24n6JtUMy#key",
        "controller": "did:iota:DadHWpApPFnGccHuK5vy1Ya4LrAUGrsnHTa24n6JtUMy",
        "type": "Ed25519VerificationKey2018",
        "publicKeyBase58": "EvxbqcfUL4HRD5B4UTKb99JvuvrDiZ4DAmKDDwgMKfkY"
      }
    ],
    "created": "2022-01-14T14:08:22Z",
    "updated": "2022-01-14T14:08:22Z",
    "proof": {
      "type": "JcsEd25519Signature2020",
      "verificationMethod": "#key",
      "signatureValue": "mPgNFMBZARNnbm9wYnvyaE5F3EhoZP364vUGTio4WLupssyDszbKM73dFgV7H8QezpmY1G2hkRBCw8PLmBTgaTE"
    }
  },
  "key": {
    "type": "ed25519",
    "public": "EvxbqcfUL4HRD5B4UTKb99JvuvrDiZ4DAmKDDwgMKfkY",
    "secret": "5KUUgkxFw2ajYBKwoTj7VDvu64bY4u2TTVcMr9WYoaGP",
    "encoding": "base58"
  }
}
```

**Comment by mastrogiovanni** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cxc-slu-authenticity-61dc34ef8e14c50019ea6358/issues/iotaledger/cxc-slu-authenticity/15?planning-poker) with ZenHub @jacekroszkowiakdev @JuriBog

**Comment by mastrogiovanni** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cxc-slu-authenticity-61dc34ef8e14c50019ea6358/issues/iotaledger/cxc-slu-authenticity/15?planning-poker) with ZenHub @dominic22

**Comment by dominic22** [comment]
As I understand:
- Write a script which calls your vpuf.
- It shall be callable via command line tool. 
- I would suggest to call it as following:
  - npm run encrypt-file 
    - which then requests to input a location of the keyfile, input which is a json file and a destination where the encrypted data shall be stored

so for instance it could look like:
```
npm run encrypt-file key-file=./config/unclonable.test.txt input=./data/slu-data.json dest=./data/slu-data.json.enc
```
