### ISSUE TITLE
Microservice: Status of SLU

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/cxc-slu-authenticity#19]
Devices are stored by the backend of the IS. But we need to store further metadata about a device like if the device is already setup or not.

IS can be used for the following use cases so no implementation needed for the backend part.
- list devices
- (PUT) update info of a device

What you need to do:

Create a microservice to manage Devices state (this will be called by one-shot-device later)

Add new microservice: *slu-status*
- (POST) Create a new slu-status entry with following fields:

```
id:string
status: StatusEnum
channelAddress:string
```

- (PUT) adjust status of a device (set it to installed)
- (GET) get the status info of a device

*StatusEnum*

**created**: create device on database and channel with subscription using the **is-one-shot-device-registration**
**installed**: is when a bootstrap is performed, nonce is lost and data are downloaded and stored in the read device

There is no authorization/authentication mechanism. Just define a mandatory API-Key.

**Comment by dominic22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/cxc-slu-authenticity-61dc34ef8e14c50019ea6358/issues/iotaledger/cxc-slu-authenticity/19?planning-poker) with ZenHub @JuriBog @jacekroszkowiakdev
