### ISSUE TITLE
T1.1	- UI Mockups + Designs by UX Team + UI Setup

### ISSUE THREAD

**Issue by mastrogiovanni** [iotaledger/cxc-slu-authenticity#2]
"- Create mockups
- Create scenarios so UX Team is able to understand the use cases better
(- Wait for UX Team designs + communicate with them)
- First UI setup with library of CxC components
(Navigation, routing..)
- Scaffolding of UI
- Create component library by using CxC components which can then be used when implementing the UI"

*Assumptions*
"We can reuse the use cases of the technical specification and hand them over to the UX team."

**Comment by dominic22** [comment]
We gave our input to UI/UX and it is an ongoing process which we will review every 2 weeks. I will close the ticket to have a better overview.
