### ISSUE TITLE
Setup Raspberry Pi

### ISSUE THREAD

**Issue by dominic22** [iotaledger/cxc-slu-authenticity#59]
- Research how to best use nodejs on a pi like for instance raspbian + nodejs, ...
- Setup raspberry pi with nodejs
- Install scripts on pi like clone repo or ship it in a different way. Research for best approach how to ship scripts to pi. Build the scripts as production
- Connect via ssh to the pi and create a file with a nonce in it.
- Trigger the scripts via command line

Write a documentation what we used to setup and how it is done.

**Comment by mastrogiovanni** [comment]
Here the Confluence page where to insert details about this work @jacekroszkowiakdev: https://iotafoundation.atlassian.net/l/c/HRskWTRz
